import { WasiCliEnvironment } from './imports/wasi-cli-environment';
import { WasiCliExit } from './imports/wasi-cli-exit';
import { WasiCliStderr } from './imports/wasi-cli-stderr';
import { WasiCliStdin } from './imports/wasi-cli-stdin';
import { WasiCliStdout } from './imports/wasi-cli-stdout';
import { WasiCliTerminalInput } from './imports/wasi-cli-terminal-input';
import { WasiCliTerminalOutput } from './imports/wasi-cli-terminal-output';
import { WasiCliTerminalStderr } from './imports/wasi-cli-terminal-stderr';
import { WasiCliTerminalStdin } from './imports/wasi-cli-terminal-stdin';
import { WasiCliTerminalStdout } from './imports/wasi-cli-terminal-stdout';
import { WasiClocksWallClock } from './imports/wasi-clocks-wall-clock';
import { WasiFilesystemPreopens } from './imports/wasi-filesystem-preopens';
import { WasiFilesystemTypes } from './imports/wasi-filesystem-types';
import { WasiIoStreams } from './imports/wasi-io-streams';
import { WasiRandomRandom } from './imports/wasi-random-random';
import { LocalWasmToolsTools } from './exports/local-wasm-tools-tools';
export const tools: typeof LocalWasmToolsTools;
